name: uniplan_cli
description: A command-line interface for UniPlan backend API testing
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  http: ^1.2.0
  ansicolor: ^2.0.2
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0

executables:
  uniplan:
