# 개발 환경 설정
server:
  port: 8080

# 마이크로서비스 URI 설정 (개발 환경 - Docker Compose 또는 K8s Service)
services:
  user-service:
    uri: ${USER_SERVICE_URI:http://user-service:8081}
  planner-service:
    uri: ${PLANNER_SERVICE_URI:http://planner-service:8082}
  catalog-service:
    uri: ${CATALOG_SERVICE_URI:http://catalog-service:8083}

# JWT 설정
jwt:
  secret: ${JWT_SECRET}

# CORS 설정
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://dev.uniplan.com}

