server:
  port: 8080

spring:
  application:
    name: api-gateway

  # Spring Cloud Gateway 설정
  cloud:
    gateway:
      # 전역 CORS 설정
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: ${CORS_ALLOWED_ORIGINS:https://uniplan.com}
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

      # 라우트 설정은 FilterConfig.java에서 프로그래밍 방식으로 관리
      routes:
        # User Service Swagger Docs 라우팅 (운영 환경에서는 비활성화 권장)
        - id: user-service-docs
          uri: ${USER_SERVICE_URI}
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/v3/api-docs, /v3/api-docs

        # Planner Service Swagger Docs 라우팅
        - id: planner-service-docs
          uri: ${PLANNER_SERVICE_URI}
          predicates:
            - Path=/planner-service/v3/api-docs
          filters:
            - RewritePath=/planner-service/v3/api-docs, /v3/api-docs

        # Catalog Service Swagger Docs 라우팅
        - id: catalog-service-docs
          uri: ${CATALOG_SERVICE_URI}
          predicates:
            - Path=/catalog-service/v3/api-docs
          filters:
            - RewritePath=/catalog-service/v3/api-docs, /v3/api-docs

# 마이크로서비스 URI 설정 (운영 환경 - K8s Service 또는 로드밸런서)
services:
  user-service:
    uri: ${USER_SERVICE_URI}
  planner-service:
    uri: ${PLANNER_SERVICE_URI}
  catalog-service:
    uri: ${CATALOG_SERVICE_URI}

# JWT 설정 (운영 환경에서는 반드시 환경변수 사용)
jwt:
  secret: ${JWT_SECRET}

# Swagger/OpenAPI 설정 (운영 환경에서는 비활성화 권장)
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SWAGGER_ENABLED:false}
    # 각 서비스의 OpenAPI 스펙 URL 지정 (드롭다운으로 선택)
    urls:
      - name: "User Service"
        url: /user-service/v3/api-docs
      - name: "Planner Service"
        url: /planner-service/v3/api-docs
      - name: "Catalog Service"
        url: /catalog-service/v3/api-docs
      - name: "Gateway (Actuator)"
        url: /v3/api-docs
    # UI에서 기본 선택될 서비스
    urls-primary-name: "User Service"
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# 로깅 설정
logging:
  level:
    root: INFO
    com.uniplan: INFO

