# 운영 환경 설정
server:
  port: 8080

# 마이크로서비스 URI 설정 (운영 환경 - K8s Service 또는 로드밸런서)
services:
  user-service:
    uri: ${USER_SERVICE_URI}
  planner-service:
    uri: ${PLANNER_SERVICE_URI}
  catalog-service:
    uri: ${CATALOG_SERVICE_URI}

# JWT 설정 (운영 환경에서는 반드시 환경변수 사용)
jwt:
  secret: ${JWT_SECRET}

# CORS 설정
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://uniplan.com}

# 로깅 설정
logging:
  level:
    root: INFO
    com.uniplan: INFO

